# .render.yaml for deploying Flask app
services:
  - type: web
    name: justworkout-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn workout:app
    envVars:
      - key: MYSQL_HOST
        value: <your-mysql-host>
      - key: MYSQL_USER
        value: <your-mysql-user>
      - key: MYSQL_PASSWORD
        value: <your-mysql-password>
      - key: MYSQL_DB
        value: workout_db
      - key: SECRET_KEY
        value: <your-secret-key>
